# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

#on事件 触发 workflow 的事件
on:
  #在本地发生push时
  push:
    branches: [ "main" ]

jobs:
  # 一个job任务，任务名为build
  build:
    #运行在最新版ubuntu系统中
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
   
    #步骤合集
    steps:
    #使用checkout@v3这个action获取源码
    - uses: actions/checkout@v2
    #新建一个名为checkout_actions的步骤
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    #执行执行某个shell命令或脚本
    - run: npm run build --if-present
    
    #关于deploy自动部署项目至阿里云的actions
    - name: Deploy
      #使用了作者开发的插件
      uses: easingthemes/ssh-deploy@v2.0.7
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
        ARGS: "-rltgoDzv0 --delete"
        #复制源是 ghpages分支下所有文件
        SOURCE: "/"
        REMOTE_HOST: "120.77.63.71"
        REMOTE_USER: "root"
        #复制至服务器目录
        TARGET: "/www/study.dt-code.fun/"
